export default ActionTypes = {
    FETCH_SONGS : "FETCH_SONGS",
    FETCH_SONGS_DONE : "FETCH_SONGS_DONE",
    SEARCH_SONGS : "SEARCH_SONGS",
    FETCH_DOWNLOADED_SONGS : "FETCH_DOWNLOADED_SONGS",
    DOWNLOAD_SONG : "DONWLOAD_SONG",
    GET_DOWNLOADED_SONGS : "GET_DOWNLOADED_SONGS",
    GET_DOWNLOADED_SONGS_SUCCESS : "GET_DOWNLOADED_SONGS_SUCCESS"
};